# Welcome to Serverless!
#
# This file is the main config file for your service.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-java-gradle # NOTE: update this with your service name

provider:
  name: aws
  runtime: java8

package:
  artifact: build/distributions/rating.zip

functions:
  getRating:
    handler: rating.handler.GetHandler
    events:
      - http:
          path: rating
          method: get
          cors: true
  createRating:
      handler: rating.handler.CreateHandler
      events:
        - http:
            path: rating
            method: post
            cors: true